# 예외처리
## 1. 예외
- 예외: 사용자의 잘못된 조작 또는 개발자의 잘못된 코딩으로 인해 발생하는 프로그램 오류
- 자바는 예외가 발생할 가능성이 높은 코드를 컴파일할 때 예외 처리 유무를 확인한다.

> 에러: 메모리 부족이나 스택 오버플로우 같이 발생하면 복구할 수 없는 심각한 오류<br>
> 예외: 발생하더라도 수습될 수 있는 비교적 덜 심각한 오류
> 
> 에러와 예외 모두 발생하면 프로그램이 비정상적으로 종료되지만, 예외는 예외처리를 통해 프로그램을 종료하지 않고 정상 실행 상태가 되도록 유지할 수 있다.

<br>

## 2. 예외 클래스
- Exception: 프로그램 실행 시 예외가 발생할 가능성이 높기 때문에 자바 소스를 컴파일하는 과정에서 해당 예외처리 코드가 있는지 검사하고, 만약 예외 처리 코드가 없다면 컴파일 오류가 발생한다.
    - FileNotFoundException, ClassNotFoundException, DataFormatException 등

<br>

- RuntimeException: 실행 시 예측할 수 없이 갑자기 발생하기 때문에 컴파일하는 과정에서 예외처리 코드가 있는지 검사하지 않는다.
  - ``NullPointException``: null 값을 갖는 참조 변수에 객체 접근 연산자를 사용한 경우
  - ``ArrayIndexOutOfBoundsException``: 배열에서 인덱스 범위를 초과한 경우
  - ``ClassCastException``: 상속 관계 또는 인터페이스와 구현 클래스 관계가 아닌 클래스 간에 타입을 변환하는 경우 (instanceof를 통해 타입 변환 전에 변환이 가능한지 확인하는 것이 좋다.)
  - ``NumberFormatException``: Wrapper 클래스의 parseXXX() 같은 메서드를 통해 문자열을 숫자로 변환하는 경우
  - ``ArithmeticException`` 등

<br>

## 3. 예외처리 (try-catch-finally)
예외처리란 생성자나 메서드 내부에 프로그램 실행 시 발생할 수 있는 예외에 대비한 코드를 작성하는 것으로, 프로그램의 비정상적인 종료를 막고 정상적인 실행상태를 유지하게 한다.

<br>

- ``try 블록``에는 예외 발생 가능 코드가 위치한다.
- try 블럭 내에서 예외가 발생하면 발생한 예외와 일치하는 ``catch 블럭``이 있는지 확인하고, 일치하는 catch 블럭이 있으면 블럭 내의 문장들을 수행하고 try-catch문을 빠져나간다.
- try 블럭에서 예외가 발생하면 이후에 있는 try 블럭의 문장들은 수행되지 않는다.
- ``finally 블럭``은 예외의 발생여부에 상관없이 실행되어야할 코드를 포함시킬 목적으로 사용하며, try 블럭이나 catch 블럭에서 return문이 실행되는 경우에도 finally 블럭의 문장들은 수행되고 메서드가 종료된다.

> printStackTrace(): 예외발생 당시의 호출스택에 있었던 메서드의 정보와 예외 메시지를 화면에 출력한다.<br>
> getMessage(): 발생한 예외클래스의 인스턴스에 저장된 메시지를 얻을 수 있다.

> try 블럭에서 동시 다발적으로 예외가 발생하지 않고, 하나의 예외가 발생하면 즉시 실행을 멈추가 해당 catch 블럭으로 이동하기 때문에 catch 블럭이 여러 개라 하더라도 위에서부터 단 하나의 catch 블럭만 실행된다.<br>
> ->  상위 예외 클래스가 하위 예외 블래스보다 아래쪽에 위치해야 한다.

<br>

## 4. 예외 떠넘기기 (throws)
- 메서드 선언부에 작성하는 throws는 메서드 내에서 발생할 수 있는 예외를 명시하는 역할과, 메서드에서 처리하지 않은 예외를 호출한 곳으로 떠넘기는 역할을 수행한다.
- **예외를 처리하는 것이 아니라, 자신을 호출한 메서드에게 예외를 전달하여 예외처리를 떠맡기는 것**이기 때문에 **throws가 붙어 있는 메서드는 반드시 try 블럭 내에서 호출**되어야 한다.

> 예외처리 위치??<br>
> 예외가 발생한 메서드 내에서 자체적으로 처리해도 되는 것은 메서드 내에서 처리<br>
> 메서드 호출 시 넘겨받아야 할 값을 다시 받아야 하는 경우와 같이 메서드 내에서 자체적으로 해결이 안 되는 경우에는 예외를 메서드에 선언해서 호출한 메서드에서 처리

<br>

## 5. try-with-resources문
- try-with-resources문의 괄호 안에 객체를 생성하는 문장을 넣으면, 이 객체는 따로 close()를 호출하지 않아도 try 블럭을 벗어나는 순간 자동적으로 close가 호출된다.
- 억제된 예외??

<br>

## 6. 사용자 정의 예외
- 기존의 예외 클래스는 주로 Exception을 상속받아서 ``checked 예외``로 작성하는 경우가 많았지만, 요즘은 예외처리를 선택적으로 할 수 있도록 RuntimeException을 상속받아서 작성한다.
- checked 예외는 반드시 예외처리를 해주어야 하기 때문에 예외처리가 불필요한 경우에도 예외처리를 해주어야 해서 코드가 복잡해지기 때문!
- 필요에 따라 예외처리의 여부를 선택할 수 있는 ``unchecked 예외``가 선호되고 있다.

<br>

## 7. 예외 되던지기
- 예외를 처리한 후에 throw문을 사용해서 인위적으로 예외를 다시 발생시켜, 예외가 발생한 메서드와 호출한 메서드 양쪽에서 처리하게 하는 방법
- 예외가 발생할 메서드에서는 예외처리를 해줌과 동시에 메서드의 선언부에 발생할 예외를 throws에 지정해줘야 한다.
